---
title: "ARS Definition"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ARS-Def}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# ARS Background

[ARS](https://www.cdisc.org/standards/foundational/analysis-results-standard) stands for Analysis Results Standard, and was released as a foundation standard by [CDISC](https://www.cdisc.org/) in April 2024.  

The ARS is a standardized way of describing analysis results (which are presented in Tables, Figures and Listings), allowing 
for automation, reproducibility and reusability of the results.  The ARS consists of a Logical Data Model that describes
analysis results and associated metadata. 

# ARS Usage

In order to make use of the ARS for Analysis Results automation, the following components are used:

## Input: 

It is important to note that 

### ARS metadata (JSON or xlsx)

It is important to note that ARS metadata is assembled
- for a single reporting event (e.g. CSR, of Publication)
- consisting of multiple Outputs
- each consisting of various Analysis (e.g. Summary Statistics by Age)

The ARS metadata is officially in JSON format, but can also be represented in xlsx-format. 


### ADaM datasets (JSON or xlsx)

The ARS metadata describes the Analysis Results structure, making use of references to ADaM datasets and variables.  
The ARS metadata can therefore exist without the actual ADaM datasets, but in order to use the ARS metadata for 
Analysis Results automation, the ADaM datasets need to be passed as a separate input.  

## Output: 

The product of utilising ARS metadata in conjunction with ADaM datasets, is the Analysis Results.  This is produced 
in a tabular format, and is known as the Analysis Results Dataset (ARD).  The ARD consists of relevant metadata, along 
with the results to be used in the final outputs.
